### ISSUE TITLE
For Code review.

### ISSUE THREAD

**Issue by Itswali** [Itswali/Recipe-App#15]
### HELLO CODE REVIEWER.

> This is a team of 2 programmers.

Programmer 1 : @Itswali .
Programmer 2 : @Balikuddembe .

 [LINK OF THE PROJECT](https://github.com/users/Itswali/projects/7)

**Comment by rloterh** [comment]
Hi Team, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on, but you are almost there! 
🏁  🌴 🚦 🚗 🏫  🏡   _🏃 🏃  🌴 🌴 

## Highlights 👍 
- Added the required number of tasks!

## Required Changes ♻️
- [ ] Tasks are unfairly distributed! Let's ensure that the difference in the total number of points of each team member is not more or less than 5.

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Itswali** [comment]
Task has been reassigned fairly.

**Comment by DammyShittu** [comment]
Hi @Itswali and @Balikuddembe,

## APPROVED 🟢

## Highlights
✔️ Evenly shared tasks

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
